require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

platform :ios, '11.0'

target 'TextExtractorExample' do
  use_unimodules!
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-text-extractor', :path => '../..'
end
